import Footer from "./components/Footer";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Business and Website Audits",
  description: "Generated by an intern at Bitropia.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <div className="grow">{children}</div>
          <Footer className="mt-auto" />
        </div>
      </body>
    </html>
  );
}
